#### Importing the Libraries

In [1]:
import pandas as pd
import numpy as np

#### Importing the Dataset

In [2]:
movies = pd.read_csv('imdb_top_1000.csv')
movies.head()

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"2,83,41,469"
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"13,49,66,411"
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"53,48,58,444"
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,A,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,"5,73,00,000"
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,U,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,"43,60,000"

In [3]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1001 entries, 0 to 1000
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Poster_Link    1000 non-null   object
 1   Series_Title   1001 non-null   object
 2   Released_Year  1001 non-null   object
 3   Certificate    900 non-null    object
 4   Runtime        1001 non-null   object
 5   Genre          1001 non-null   object
 6   IMDB_Rating    1001 non-null   float64
 7   Overview       1001 non-null   object
 8   Meta_score     844 non-null    float64
 9   Director       1001 non-null   object
 10  Star1          1001 non-null   object
 11  Star2          1001 non-null   object
 12  Star3          1001 non-null   object
 13  Star4          1001 non-null   object
 14  No_of_Votes    1001 non-null   int64
 15  Gross          832 non-null    object
dtypes: float64(2), int64(1), object(13)
memory usage: 125.2+ KB

#### Filtering out necessary attributes necessary in Movie Recommendation

In [4]:
# Series_Title 
# Released_Year 
# Certificate
# Genre 
# Overview
# Director
# Star1
# Star2
# Star3
# Star4

In [5]:
movies = movies[['Series_Title', 'Released_Year', 'Certificate', 'Genre', 'Overview', 'Director', 'Star1', 'Star2', 'Star3', 'Star4']]
movies.head()

,Series_Title,Released_Year,Certificate,Genre,Overview,Director,Star1,Star2,Star3,Star4
0,The Shawshank Redemption,1994,A,Drama,Two imprisoned men bond over a number of years...,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler
1,The Godfather,1972,A,"Crime, Drama",An organized crime dynasty's aging patriarch t...,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton
2,The Dark Knight,2008,UA,"Action, Crime, Drama",When the menace known as the Joker wreaks havo...,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine
3,The Godfather: Part II,1974,A,"Crime, Drama",The early life and career of Vito Corleone in ...,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton
4,12 Angry Men,1957,U,"Crime, Drama",A jury holdout attempts to prevent a miscarria...,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler

#### Checking missing Values in the data

In [6]:
movies.isnull().sum()

Series_Title       0
Released_Year      0
Certificate      101
Genre              0
Overview           0
Director           0
Star1              0
Star2              0
Star3              0
Star4              0
dtype: int64

#### Imputing missing values

In [7]:
movies['Certificate'].mode()

0    U
Name: Certificate, dtype: object

In [8]:
movies['Certificate'].fillna('U', inplace=True)

In [9]:
movies.isnull().sum()

Series_Title     0
Released_Year    0
Certificate      0
Genre            0
Overview         0
Director         0
Star1            0
Star2            0
Star3            0
Star4            0
dtype: int64

In [10]:
movies.shape

(1001, 10)

In [11]:
movies.duplicated().sum()

0

In [12]:
movies.head()

,Series_Title,Released_Year,Certificate,Genre,Overview,Director,Star1,Star2,Star3,Star4
0,The Shawshank Redemption,1994,A,Drama,Two imprisoned men bond over a number of years...,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler
1,The Godfather,1972,A,"Crime, Drama",An organized crime dynasty's aging patriarch t...,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton
2,The Dark Knight,2008,UA,"Action, Crime, Drama",When the menace known as the Joker wreaks havo...,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine
3,The Godfather: Part II,1974,A,"Crime, Drama",The early life and career of Vito Corleone in ...,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton
4,12 Angry Men,1957,U,"Crime, Drama",A jury holdout attempts to prevent a miscarria...,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler

#### Transforming necessary columns values to list of single worded strings

In [13]:
movies['Genre'] = movies['Genre'].apply(lambda x:x.split())
movies['Overview'] = movies['Overview'].apply(lambda x:x.split())
movies['Director'] = movies['Director'].apply(lambda x:x.split())
movies['Star1'] = movies['Star1'].apply(lambda x:x.split())
movies['Star2'] = movies['Star2'].apply(lambda x:x.split())
movies['Star3'] = movies['Star3'].apply(lambda x:x.split())
movies['Star4'] = movies['Star4'].apply(lambda x:x.split())
movies.head()

,Series_Title,Released_Year,Certificate,Genre,Overview,Director,Star1,Star2,Star3,Star4
0,The Shawshank Redemption,1994,A,[Drama],"[Two, imprisoned, men, bond, over, a, number, ...","[Frank, Darabont]","[Tim, Robbins]","[Morgan, Freeman]","[Bob, Gunton]","[William, Sadler]"
1,The Godfather,1972,A,"[Crime,, Drama]","[An, organized, crime, dynasty's, aging, patri...","[Francis, Ford, Coppola]","[Marlon, Brando]","[Al, Pacino]","[James, Caan]","[Diane, Keaton]"
2,The Dark Knight,2008,UA,"[Action,, Crime,, Drama]","[When, the, menace, known, as, the, Joker, wre...","[Christopher, Nolan]","[Christian, Bale]","[Heath, Ledger]","[Aaron, Eckhart]","[Michael, Caine]"
3,The Godfather: Part II,1974,A,"[Crime,, Drama]","[The, early, life, and, career, of, Vito, Corl...","[Francis, Ford, Coppola]","[Al, Pacino]","[Robert, De, Niro]","[Robert, Duvall]","[Diane, Keaton]"
4,12 Angry Men,1957,U,"[Crime,, Drama]","[A, jury, holdout, attempts, to, prevent, a, m...","[Sidney, Lumet]","[Henry, Fonda]","[Lee, J., Cobb]","[Martin, Balsam]","[John, Fiedler]"

#### Removing spaces if any

In [14]:
# Define a function called "collapse" that takes a list "L" as an argument
def collapse(L):
    # Create an empty list called "L1"
    L1 = []
    # Iterate through each element in the input list "L"
    for i in L:
        # Remove any whitespace characters (i.e. spaces) from the current element using the "replace()" method with an empty string as the second argument
        # Then append the modified element to the "L1" list
        L1.append(i.replace(" ",""))
    # Return the modified list "L1"
    return L1

In [15]:
movies['Genre'] = movies['Genre'].apply(collapse)
movies['Director'] = movies['Director'].apply(collapse)
movies['Overview'] = movies['Overview'].apply(collapse)

In [16]:
movies.head()

,Series_Title,Released_Year,Certificate,Genre,Overview,Director,Star1,Star2,Star3,Star4
0,The Shawshank Redemption,1994,A,[Drama],"[Two, imprisoned, men, bond, over, a, number, ...","[Frank, Darabont]","[Tim, Robbins]","[Morgan, Freeman]","[Bob, Gunton]","[William, Sadler]"
1,The Godfather,1972,A,"[Crime,, Drama]","[An, organized, crime, dynasty's, aging, patri...","[Francis, Ford, Coppola]","[Marlon, Brando]","[Al, Pacino]","[James, Caan]","[Diane, Keaton]"
2,The Dark Knight,2008,UA,"[Action,, Crime,, Drama]","[When, the, menace, known, as, the, Joker, wre...","[Christopher, Nolan]","[Christian, Bale]","[Heath, Ledger]","[Aaron, Eckhart]","[Michael, Caine]"
3,The Godfather: Part II,1974,A,"[Crime,, Drama]","[The, early, life, and, career, of, Vito, Corl...","[Francis, Ford, Coppola]","[Al, Pacino]","[Robert, De, Niro]","[Robert, Duvall]","[Diane, Keaton]"
4,12 Angry Men,1957,U,"[Crime,, Drama]","[A, jury, holdout, attempts, to, prevent, a, m...","[Sidney, Lumet]","[Henry, Fonda]","[Lee, J., Cobb]","[Martin, Balsam]","[John, Fiedler]"

#### Combining all the necessary columns that will help in Movie Recommendation

In [17]:
movies['recommender'] = movies['Genre'] + movies['Overview'] + movies['Director'] + movies['Star1'] + movies['Star2'] + movies['Star3'] + movies['Star4']
movies.head()

,Series_Title,Released_Year,Certificate,Genre,Overview,Director,Star1,Star2,Star3,Star4,recommender
0,The Shawshank Redemption,1994,A,[Drama],"[Two, imprisoned, men, bond, over, a, number, ...","[Frank, Darabont]","[Tim, Robbins]","[Morgan, Freeman]","[Bob, Gunton]","[William, Sadler]","[Drama, Two, imprisoned, men, bond, over, a, n..."
1,The Godfather,1972,A,"[Crime,, Drama]","[An, organized, crime, dynasty's, aging, patri...","[Francis, Ford, Coppola]","[Marlon, Brando]","[Al, Pacino]","[James, Caan]","[Diane, Keaton]","[Crime,, Drama, An, organized, crime, dynasty'..."
2,The Dark Knight,2008,UA,"[Action,, Crime,, Drama]","[When, the, menace, known, as, the, Joker, wre...","[Christopher, Nolan]","[Christian, Bale]","[Heath, Ledger]","[Aaron, Eckhart]","[Michael, Caine]","[Action,, Crime,, Drama, When, the, menace, kn..."
3,The Godfather: Part II,1974,A,"[Crime,, Drama]","[The, early, life, and, career, of, Vito, Corl...","[Francis, Ford, Coppola]","[Al, Pacino]","[Robert, De, Niro]","[Robert, Duvall]","[Diane, Keaton]","[Crime,, Drama, The, early, life, and, career,..."
4,12 Angry Men,1957,U,"[Crime,, Drama]","[A, jury, holdout, attempts, to, prevent, a, m...","[Sidney, Lumet]","[Henry, Fonda]","[Lee, J., Cobb]","[Martin, Balsam]","[John, Fiedler]","[Crime,, Drama, A, jury, holdout, attempts, to..."

In [18]:
new_movies = movies.drop(labels = ['Genre', 'Overview', 'Director', 'Star1', 'Star2', 'Star3', 'Star4', 'Released_Year', 'Certificate'], axis = 1)
new_movies.head()

               Series_Title                                        recommender
0  The Shawshank Redemption  [Drama, Two, imprisoned, men, bond, over, a, n...
1             The Godfather  [Crime,, Drama, An, organized, crime, dynasty'...
2           The Dark Knight  [Action,, Crime,, Drama, When, the, menace, kn...
3    The Godfather: Part II  [Crime,, Drama, The, early, life, and, career,...
4              12 Angry Men  [Crime,, Drama, A, jury, holdout, attempts, to...

#### Converting list again to string

In [19]:
new_movies['recommender'] = new_movies['recommender'].apply(lambda x:" ".join(x))
new_movies['recommender'] = new_movies['recommender'].apply(lambda x:x.lower())
new_movies.head()

               Series_Title                                        recommender
0  The Shawshank Redemption  drama two imprisoned men bond over a number of...
1             The Godfather  crime, drama an organized crime dynasty's agin...
2           The Dark Knight  action, crime, drama when the menace known as ...
3    The Godfather: Part II  crime, drama the early life and career of vito...
4              12 Angry Men  crime, drama a jury holdout attempts to preven...

#### Stemming words that have almost similar meaning

In [20]:
from nltk.stem.porter import PorterStemmer
stemmer = PorterStemmer()

In [21]:
def stem(text):
    L = []
    for i in text.split():
        L.append(stemmer.stem(i))
        
    return " ".join(L)

In [22]:
new_movies['recommender'] = new_movies['recommender'].apply(stem)

In [23]:
new_movies['recommender'][34]

"drama, music a promis young drummer enrol at a cut-throat music conservatori where hi dream of great are mentor by an instructor who will stop at noth to realiz a student' potential. damien chazel mile teller j.k. simmon melissa benoist paul reiser"

#### Fetching top most occuring 3000 words in recommender column and vectorising them

In [24]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer(max_features = 3000, stop_words='english', )

In [25]:
vectors = vectorizer.fit_transform(new_movies['recommender']).toarray()

In [26]:
vectors.shape

(1001, 3000)

In [27]:
vectorizer.get_feature_names()

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

['000',
 '007',
 '10',
 '12',
 '1920',
 '1925',
 '1930',
 '1930s',
 '1936',
 '1940s',
 '1950',
 '1960',
 '1960s',
 '1962',
 '1969',
 '1970',
 '1970s',
 '1980',
 '1984',
 '1985',
 '1990',
 '20',
 '2013',
 '21',
 '24',
 '40',
 'aamir',
 'aaron',
 'abandon',
 'abduct',
 'abhay',
 'abhishek',
 'abil',
 'abl',
 'aboard',
 'abraham',
 'abram',
 'abus',
 'accept',
 'accid',
 'accident',
 'accompani',
 'account',
 'accus',
 'achiev',
 'acquir',
 'act',
 'action',
 'activ',
 'activist',
 'actor',
 'actress',
 'actual',
 'adam',
 'adamson',
 'adapt',
 'addict',
 'adil',
 'aditya',
 'adjust',
 'adolf',
 'adopt',
 'adrien',
 'advanc',
 'advani',
 'adventur',
 'adventure',
 'advisor',
 'adèl',
 'affair',
 'affect',
 'affleck',
 'affluent',
 'africa',
 'african',
 'ag',
 'age',
 'agent',
 'ago',
 'agre',
 'ahm',
 'aid',
 'aiello',
 'aimé',
 'air',
 'ajay',
 'akbag',
 'akhtar',
 'akin',
 'akira',
 'akshay',
 'al',
 'alabama',
 'alain',
 'alan',
 'albert',
 'alcohol',
 'aldo',
 'aldrich',
 'alec',
 'alejandro',
 'aleksandr',
 'aleksey',
 'alex',
 'alexand',
 'alexandr',
 'alexandra',
 'alfonso',
 'alfr',
 'ali',
 'alia',
 'alibi',
 'alida',
 'alidoosti',
 'alien',
 'alison',
 'allen',
 'alli',
 'allianc',
 'allies',
 'allow',
 'almodóvar',
 'alon',
 'alongsid',
 'alter',
 'altieri',
 'altman',
 'amalr',
 'aman',
 'amateur',
 'ambiti',
 'amenábar',
 'america',
 'american',
 'ami',
 'amin',
 'amir',
 'amit',
 'amitabh',
 'ana',
 'anand',
 'anatolian',
 'anatoliy',
 'ancient',
 'ander',
 'anderson',
 'andersson',
 'andi',
 'andrea',
 'andrei',
 'andrew',
 'andrey',
 'andré',
 'ang',
 'angel',
 'angela',
 'angeles',
 'angelina',
 'ani',
 'anil',
 'animation',
 'aniston',
 'ann',
 'anna',
 'annaud',
 'anni',
 'anno',
 'annoy',
 'anonym',
 'anoth',
 'anouk',
 'ansel',
 'answer',
 'anthoni',
 'anthropomorph',
 'anti',
 'antoin',
 'anton',
 'antonio',
 'antonioni',
 'anupam',
 'anurag',
 'anushka',
 'anyon',
 'anyth',
 'aoi',
 'apart',
 'apartment',
 'ape',
 'apocalypt',
 'apollo',
 'appear',
 'appoint',
 'approach',
 'arab',
 'area',
 'argu',
 'aristocrat',
 'arkin',
 'arm',
 'arma',
 'armi',
 'armin',
 'armitag',
 'armstrong',
 'army',
 'arnold',
 'aronofski',
 'arquett',
 'arrang',
 'arrest',
 'arriv',
 'arrives',
 'arshad',
 'art',
 'arthur',
 'artist',
 'ascens',
 'asghar',
 'ashbi',
 'ashutosh',
 'ask',
 'aspir',
 'assassin',
 'assault',
 'assembl',
 'assign',
 'assist',
 'assum',
 'astronaut',
 'athlet',
 'attack',
 'attempt',
 'attenborough',
 'attend',
 'attention',
 'attorney',
 'attract',
 'audrey',
 'august',
 'aunt',
 'australian',
 'author',
 'authorities',
 'aveng',
 'avengers',
 'averi',
 'avoid',
 'await',
 'awaken',
 'away',
 'aykroyd',
 'ayushmann',
 'babi',
 'bacal',
 'baccarin',
 'bachchan',
 'bachelor',
 'bacon',
 'baggin',
 'bahar',
 'bajpaye',
 'baker',
 'balan',
 'baldwin',
 'bale',
 'balsam',
 'bamboo',
 'bana',
 'bancroft',
 'band',
 'bandit',
 'bandits',
 'bank',
 'banker',
 'barbara',
 'bardem',
 'bare',
 'barkhad',
 'barr',
 'barri',
 'barrymor',
 'baruchel',
 'base',
 'basebal',
 'bate',
 'bateman',
 'batman',
 'battl',
 'battle',
 'baumbach',
 'bautista',
 'baxter',
 'beach',
 'bear',
 'beatti',
 'beauti',
 'becam',
 'becaus',
 'becom',
 'befor',
 'befriend',
 'begin',
 'behavior',
 'bejo',
 'bel',
 'belgium',
 'believ',
 'bell',
 'belov',
 'belén',
 'ben',
 'beneath',
 'benedict',
 'benicio',
 'benigni',
 'benjamin',
 'bennett',
 'benson',
 'benton',
 'bereng',
 'bergman',
 'berlin',
 'bernal',
 'bernardo',
 'bernhard',
 'bernstein',
 'bernthal',
 'bertolucci',
 'besson',
 'best',
 'betray',
 'bett',
 'better',
 'bhatt',
 'bibi',
 'biehn',
 'bier',
 'big',
 'bilbo',
 'bilg',
 'billi',
 'billingsley',
 'billy',
 'bin',
 'biograph',
 'biographi',
 'biography',
 'bird',
 'birgitta',
 'birthday',
 'bitter',
 'bizarr',
 'björk',
 'björnstrand',
 'black',
 'blackmail',
 'blade',
 'blake',
 'blame',
 'blanchett',
 'bleibtreu',
 'blethyn',
 'blind',
 'blond',
 'blood',
 'bloodi',
 'bloom',
 'blossom',
 'blue',
 'blunt',
 'blur',
 'bo',
 'board',
 'boat',
 'bob',
 'bodi',
 'body',
 'bogart',
 'bogdanovich',
 'bond',
 'bong',
 'bonni',
 'book',
 'border',
 'born',
 'boss',
 'boston',
 'bounti',
 'box',
 'boxer',
 'boy',
 'boyd',
 'boyfriend',
 'boyl',
 'brad',
 'bradley',
 'brando',
 'break',
 'brenda',
 'brendan',
 'brian',
 'bride',
 'bridg',
 'brie',
 'brien',
 'brilliant',
 'bring',
 'british',
 'broadway',
 'broderick',
 'brodi',
 'brolin',
 'bronson',
 'brook',
 'brother',
 'brown',
 'bruce',
 'bruno',
 'brutal',
 'bryan',
 'buddi',
 'build',
 'bulli',
 'bullock',
 'bureaucrat',
 'buri',
 'burt',
 'burton',
 'busi',
 'business',
 'businessman',
 'buster',
 'butler',
 'buñuel',
 'byrn',
 'byron',
 'caan',
 'cab',
 'cabin',
 'cage',
 'cain',
 'california',
 'cameron',
 'camp',
 'campaign',
 'cancer',
 'capra',
 'captain',
 'captiv',
 'captur',
 'car',
 'cardinal',
 'care',
 'career',
 'carel',
 'carey',
 'cari',
 'carl',
 'carlo',
 'carol',
 'carpent',
 'carradin',
 'carri',
 'carrol',
 'case',
 'cash',
 'casino',
 'cassavet',
 'cassel',
 'cast',
 'castl',
 'castle',
 'catch',
 'cate',
 'catherin',
 'cathol',
 'caught',
 'caus',
 'cave',
 'cazal',
 'center',
 'centuri',
 'challeng',
 'champion',
 'chan',
 'chanc',
 'chang',
 'chao',
 'chaotic',
 'chaplin',
 'chapman',
 'charact',
 'charg',
 'charl',
 'charli',
 'charliz',
 'charlton',
 'chase',
 'chastain',
 'check',
 'chelsea',
 'chemic',
 'chen',
 'cheung',
 'chiaki',
 'chicago',
 'chico',
 'chief',
 'chieko',
 'child',
 'childhood',
 'children',
 'china',
 'chines',
 'chiu',
 'chiwetel',
 'chloë',
 'cho',
 'choi',
 'chopra',
 'chow',
 'chri',
 'christi',
 'christian',
 'christma',
 'christoph',
 'chronicl',
 'church',
 'cia',
 'circus',
 'citi',
 'city',
 'civil',
 'claim',
 'clair',
 'clan',
 'clark',
 'class',
 'classic',
 'classmat',
 'claud',
 'claudia',
 'clear',
 'clement',
 'clint',
 'clive',
 'clock',
 'clooney',
 'close',
 'clouzot',
 'clue',
 'cobb',
 'coen',
 'coerc',
 'cold',
 'colin',
 'colleagu',
 'collect',
 'collector',
 'colleg',
 'college',
 'collett',
 'collid',
 'come',
 'comedi',
 'comedy',
 'command',
 'commit',
 'common',
 'commun',
 'community',
 'compani',
 'companion',
 'compet',
 'complet',
 'complex',
 'complic',
 'conduct',
 'conflict',
 'confront',
 'connect',
 'connelli',
 'conneri',
 'connor',
 'considin',
 'continu',
 'control',
 'convent',
 'convict',
 'convinc',
 'cook',
 'cooper',
 'cop',
 'coppola',
 'corey',
 'corner',
 'coronado',
 'corpor',
 'corrupt',
 'corruption',
 'cortaz',
 'costner',
 'cotillard',
 'cotten',
 'count',
 'counter',
 'countri',
 'country',
 'countrymen',
 'countrysid',
 'coupl',
 'couple',
 'courag',
 'cours',
 'court',
 'cousin',
 'cover',
 'cox',
 'crafti',
 'craig',
 'cranston',
 'crash',
 'creat',
 'crew',
 'cricket',
 'crime',
 'crimes',
 'crimin',
 'crisi',
 'cross',
 'crow',
 'crudup',
 'cruis',
 'cruz',
 'crystal',
 'cuarón',
 'cukor',
 'culprit',
 'cultur',
 'curs',
 'curti',
 'cusack',
 'custodi',
 'cyborg',
 'cynic',
 'dafo',
 'daggubati',
 'daili',
 'dakota',
 'damon',
 'dan',
 'dana',
 'dancer',
 'danger',
 'daniel',
 'danni',
 'dare',
 'dark',
 'darren',
 'darth',
 'daughter',
 'dave',
 'davi',
 'david',
 'day',
 'dead',
 'deadli',
 'deal',
 'dealer',
 'dean',
 'death',
 'deborah',
 'decad',
 'decades',
 'decid',
 'dee',
 'deep',
 'defeat',
 'defend',
 'defens',
 'del',
 'deliv',
 'delpi',
 'delv',
 'demm',
 'demon',
 'dench',
 'deneuv',
 'deni',
 'denmark',
 'denni',
 'denzel',
 'depp',
 'depress',
 'depression',
 'dern',
 'desert',
 'design',
 'desper',
 'despit',
 'destin',
 'destroy',
 'destruct',
 'detect',
 'determin',
 'devast',
 'develop',
 'devic',
 'dian',
 'diann',
 'dicaprio',
 'dick',
 'did',
 'die',
 'diego',
 'dies',
 'diesel',
 'differ',
 'differences',
 'difficult',
 'dillon',
 'dimens',
 'dinner',
 'director',
 'disappear',
 'disastr',
 'discov',
 'discoveri',
 'discuss',
 'disease',
 'disillus',
 'dispatch',
 'disrupt',
 'distant',
 'distress',
 'divid',
 'divorc',
 'docter',
 'doctor',
 'doesn',
 'dog',
 'domhnal',
 'domin',
 'dominiqu',
 'don',
 'donald',
 'donna',
 'donni',
 'doom',
 'dorothi',
 'doubl',
 'doug',
 'dougla',
 'downey',
 'dr',
 'dragon',
 'drama',
 'dream',
 'drifter',
 'drink',
 'drive',
 'driver',
 'drug',
 'duk',
 'dunaway',
 'duncan',
 'dure',
 'dustin',
 'dutt',
 'duval',
 'earl',
 'earli',
 'earn',
 'earth',
 'east',
 'eastwood',
 'eccentr',
 'ed',
 'eddi',
 'edgar',
 'edward',
 'effort',
 'ego',
 'ejiofor',
 'elderli',
 'eleanor',
 'elena',
 'eli',
 'elia',
 'elijah',
 'elit',
 'elizabeth',
 'ellen',
 'elliott',
 'elw',
 'embark',
 'emerg',
 'emili',
 'emilio',
 'emir',
 'emma',
 'emmanuel',
 'emori',
 'emot',
 'emperor',
 'empir',
 'empire',
 'employ',
 'employe',
 'employer',
 'empti',
 'encount',
 'end',
 'endur',
 'enemi',
 'engag',
 'england',
 'english',
 'enlist',
 'enriqu',
 'enrol',
 'ensu',
 'ensur',
 'enter',
 'enterpris',
 'enthral',
 'entir',
 'enzo',
 'epic',
 'epidem',
 'equip',
 'era',
 'erdem',
 'erdogan',
 'eric',
 'erich',
 'erik',
 'ernest',
 'ernst',
 'escal',
 'escap',
 'estrang',
 'ethan',
 'europe',
 'evan',
 'event',
 'eventu',
 'everi',
 'everyth',
 'evil',
 'ewan',
 'ex',
 'exact',
 'examin',
 'execut',
 'exist',
 'experi',
 'expert',
 'explor',
 'expos',
 'extraordinari',
 'extraterrestri',
 'extrem',
 'eye',
 'face',
 'fact',
 'fade',
 'fail',
 'fall',
 'fame',
 'famili',
 'family',
 'famou',
 'fan',
 'fanat',
 'fantasi',
 'fantasy',
 'farhadi',
 'farhan',
 'farm',
 'farmer',
 'farrow',
 'fat',
 'fate',
 'father',
 'fay',
 'fbi',
 'fear',
 'feder',
 'federico',
 'feel',
 'feldman',
 'fellini',
 'fellow',
 'femal',
 'fernando',
 'feud',
 'fi',
 'fiction',
 'fienn',
 'fight',
 'fighter',
 'figur',
 'film',
 'final',
 'fincher',
 'firth',
 'fisher',
 'flee',
 'fleme',
 'flesh',
 'fli',
 'focus',
 'follow',
 'fonda',
 'foot',
 'forc',
 'ford',
 'forest',
 'forev',
 'form',
 'forti',
 'fortun',
 'foss',
 'foster',
 'fox',
 'foxx',
 'frame',
 'franc',
 'france',
 'franci',
 'francisco',
 'frank',
 'franka',
 'franklin',
 'françoi',
 'fred',
 'free',
 'freedom',
 'freeman',
 'french',
 'friend',
 'friends',
 'friendship',
 'frost',
 'frustrat',
 'fuel',
 'fujiwara',
 'fulfil',
 'futur',
 'future',
 'gabriel',
 'gael',
 'game',
 'gandalf',
 'gandhi',
 'gang',
 'gangster',
 'ganz',
 'garcia',
 'garcía',
 'gareth',
 'garfield',
 'gari',
 'garner',
 'garrett',
 'gaspard',
 'gather',
 'gautam',
 'gavin',
 'gay',
 'gayatri',
 'gena',
 'gene',
 'gener',
 'genet',
 'geoffrey',
 'georg',
 'gerard',
 'gere',
 'german',
 'germani',
 'getaway',
 'ghetto',
 'ghost',
 'giamatti',
 'gian',
 'giant',
 'gibson',
 'gielgud',
 'gift',
 'gil',
 'gill',
 'gilliam',
 'ginnif',
 'girl',
 'girlfriend',
 'giulietta',
 'giusepp',
 ...]

#### Calculating distance of each word with that from every word and forming a matrix for the same

In [28]:
# Import the "cosine_similarity" function from the "pairwise" module in the "metrics" package of the "sklearn" library
from sklearn.metrics.pairwise import cosine_similarity
# Compute the cosine similarity matrix of the input matrix "vectors" using the "cosine_similarity" function
similarity = cosine_similarity(vectors)

#### Function to print the similar movies

In [29]:
# Define a function called "recommend" that takes a movie title as an argument
def recommend(movie):
     # Get the index of the first matching movie in the DataFrame
    movie_index = movies[movies['Series_Title'] == movie].index[0]
    # Get the row of cosine similarity values between the input movie and all other movies in the "similarity" matrix
    distance = similarity[movie_index]
    # Sort the cosine similarity values in descending order and get the indices of the six most similar movies (excluding the input movie itself)
    movies_list = sorted(list(enumerate(distance)), reverse=True, key=lambda x:x[1])[1:7]
    # Loop through the indices of the six most similar movies and print their titles
    for i in movies_list:
        print(new_movies.iloc[i[0]].Series_Title)

In [30]:
recommend('The Dark Knight')

The Avengers
Captain America: Civil War
Avengers: Infinity War
The Fifth Element
Avengers: Endgame
Edge of Tomorrow

#### Deploying Movies Recommnedation System

In [31]:
import pickle

In [32]:
#### Converting dataframe to dictionary of movies and then pickling it
pickle.dump(new_movies.to_dict(),open('movies_dict.pkl','wb'))

In [33]:
pickle.dump(similarity,open('similarity.pkl','wb'))